"""drop_tp2_column

Revision ID: 5bee066f336e
Revises: ff7f43ce4818
Create Date: 2026-04-17 22:04:09.549094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bee066f336e'
down_revision: Union[str, None] = 'ff7f43ce4818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_signals', 'tp2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_signals', sa.Column('tp2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
