"""add_signal_candle_id_relations

Revision ID: 603ecb276d79
Revises: 25b3c87d3602
Create Date: 2026-04-27 20:11:24.535568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603ecb276d79'
down_revision: Union[str, None] = '25b3c87d3602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candle_patterns', sa.Column('signal_id', sa.Integer(), nullable=True))
    op.add_column('trade_orders', sa.Column('candle_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_orders', 'candle_id')
    op.drop_column('candle_patterns', 'signal_id')
    # ### end Alembic commands ###
