"""sync_model_changes

Revision ID: 60fe6ff22bae
Revises: b7e4f9a21c08
Create Date: 2026-06-23 22:17:16.877715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60fe6ff22bae'
down_revision: Union[str, None] = 'b7e4f9a21c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_signals_xauusd')
    op.alter_column('trade_orders', 'order_kind',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'market'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade_orders', 'order_kind',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'market'::character varying"))
    op.create_table('trade_signals_xauusd',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('signal', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('sl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tp1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trend_h1', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('ema_50_h1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ema_200_h1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('in_support', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('in_resistance', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('atr_h1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('open_m5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('high_m5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('low_m5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('close_m5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('volume_m5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ema_50_m5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ema_200_m5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rsi_m5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('atr_m5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('has_bull_pattern', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('has_bear_pattern', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp_h1', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('timestamp_m5', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('rsi_h1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('adx_h1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bbw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('jam_utc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='trade_signals_xauusd_pkey')
    )
    # ### end Alembic commands ###
