"""add_entry_target_to_trade_orders

Revision ID: ff7f43ce4818
Revises: c9d52201c0ef
Create Date: 2026-04-14 01:07:53.558903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff7f43ce4818'
down_revision: Union[str, None] = 'c9d52201c0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_orders', sa.Column('expire_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_orders', 'expire_at')
    # ### end Alembic commands ###
